
stages:  
  - build

build-job:
  stage: build
  image: docker:stable

  services:
    - docker:dind

  variables:
    IMAGE_TAG: $CI_REGISTRY/$CI_REGISTRY_GROUP/$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  
  script:
    - docker build -t $IMAGE_TAG .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $IMAGE_TAG 

