
stages:  
  - build

build-job:
  stage: build
  image: docker:stable

  services:
    - docker:dind

  variables:
    IMAGE_TAG: $CI_REGISTRY/$CI_REGISTRY_GROUP/$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  
  script:
    - echo  $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    - echo  $IMAGE_TAG
    - echo $CI_REGISTRY
    - echo  $CI_REGISTRY_USER
    - echo  $CI_REGISTRY_PASSWORD
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG 

