definitions:
<<<<<<< HEAD
  request.MerchantBillpaymentRequest:
=======
  models.QRGenerateRequest:
>>>>>>> e62476a (QRGen wiht Golang)
    properties:
      amount:
        type: number
      reference1:
        type: string
      reference2:
        type: string
    type: object
<<<<<<< HEAD
  request.MerchantPromptpayRequest:
    properties:
      amount:
        type: number
      onetime:
        type: boolean
      recieveId:
        type: string
    type: object
=======
>>>>>>> e62476a (QRGen wiht Golang)
info:
  contact: {}
paths:
  /:
    get:
      consumes:
      - application/json
      description: Health checking for the service
      operationId: HealthCheckHandler
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Health Check
<<<<<<< HEAD
  /merchant-billpayment-qr:
=======
  /qrgen:
>>>>>>> e62476a (QRGen wiht Golang)
    post:
      consumes:
      - application/json
      description: For Generate TQR
<<<<<<< HEAD
      operationId: TQR Merchant Billpayment
      parameters:
      - description: Body for Generate TQR
        in: body
        name: request.MerchantBillpaymentRequest
        required: true
        schema:
          $ref: '#/definitions/request.MerchantBillpaymentRequest'
=======
      operationId: TQRGen
      parameters:
      - description: Body for Generate TQR
        in: body
        name: models.QRGenerateRequest
        required: true
        schema:
          $ref: '#/definitions/models.QRGenerateRequest'
>>>>>>> e62476a (QRGen wiht Golang)
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
<<<<<<< HEAD
      summary: TQR Billpayment generate
  /merchant-promptpay-qr:
    post:
      consumes:
      - application/json
      description: For Generate TQR
      operationId: TQR Promptpay Promptpay
      parameters:
      - description: Body for Generate TQR
        in: body
        name: request.MerchantPromptpayRequest
        required: true
        schema:
          $ref: '#/definitions/request.MerchantPromptpayRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: TQR Promptpay generate
=======
      summary: TQR generate
>>>>>>> e62476a (QRGen wiht Golang)
swagger: "2.0"
