definitions:
  request.MerchantBillpaymentRequest:
    properties:
      amount:
        type: number
      reference1:
        type: string
      reference2:
        type: string
    type: object
  request.MerchantPromptpayRequest:
    properties:
      amount:
        type: number
      onetime:
        type: boolean
      recieveId:
        type: string
    type: object
info:
  contact: {}
paths:
  /:
    get:
      consumes:
      - application/json
      description: Health checking for the service
      operationId: HealthCheckHandler
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Health Check
  /merchant-billpayment-qr:
    post:
      consumes:
      - application/json
      description: For Generate TQR
      operationId: TQR Merchant Billpayment
      parameters:
      - description: Body for Generate TQR
        in: body
        name: request.MerchantBillpaymentRequest
        required: true
        schema:
          $ref: '#/definitions/request.MerchantBillpaymentRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: TQR Billpayment generate
  /merchant-promptpay-qr:
    post:
      consumes:
      - application/json
      description: For Generate TQR
      operationId: TQR Promptpay Promptpay
      parameters:
      - description: Body for Generate TQR
        in: body
        name: request.MerchantPromptpayRequest
        required: true
        schema:
          $ref: '#/definitions/request.MerchantPromptpayRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: TQR Promptpay generate
swagger: "2.0"
